// Generated by CoffeeScript 1.8.0
new Command({
  name: "background",
  help: "sets the provided image URL as background image for typestart.io window",
  init: function() {
    var bg;
    bg = typestart.datastore.get("background", "image");
    if ((bg != null) && bg.length > 0) {
      return document.body.style.background = "url(" + bg + ") no-repeat center center / cover fixed";
    }
  },
  f: function(arg) {
    if (arg.length > 0) {
      document.body.style.background = "url(" + arg + ") no-repeat center center / cover fixed";
      return typestart.datastore.set("background", "image", arg);
    } else {
      document.body.style.background = "hsl(200,50%,30%)";
      return typestart.datastore.get("background", "image", arg);
    }
  }
});
