// Generated by CoffeeScript 1.8.0
new Command({
  name: "todo",
  help: "A command-line todo list",
  f: function(arg) {
    var err, i, list, num, s, task, _i, _j, _ref, _ref1;
    s = typestart.splitArg(arg);
    try {
      list = typestart.datastore.get("todo", "list");
    } catch (_error) {
      err = _error;
    }
    if (list == null) {
      list = [];
    }
    switch (s.length) {
      case 0:
        if (list.length === 0) {
          return "Nothing to do!";
        } else {
          for (i = _i = 0, _ref = list.length - 1; _i <= _ref; i = _i += 1) {
            if (list[i] != null) {
              typestart.echo("" + (i + 1) + ". " + list[i]);
            }
          }
        }
        break;
      case 1:
      case 2:
        num = parseInt(s[0]);
        if (!Number.isNaN(num) && num > 0) {
          switch (s[1]) {
            case "done":
              task = list[num - 1];
              list[num - 1] = null;
              typestart.datastore.set("todo", "list", list);
              return "Task done: " + num + ". " + task;
          }
        } else {
          switch (s[0]) {
            case "done":
              break;
            default:
              for (i = _j = 0, _ref1 = list.length - 1; _j <= _ref1; i = _j += 1) {
                if (list[i] == null) {
                  list[i] = arg;
                  typestart.datastore.set("todo", "list", list);
                  return "New task: " + (i + 1) + ". " + arg;
                }
              }
              list.push(arg);
              typestart.datastore.set("todo", "list", list);
              return "New task: " + list.length + ". " + arg;
          }
        }
    }
  }
});
