// Generated by CoffeeScript 1.8.0
this.Drive = (function() {
  function Drive(main) {
    this.main = main;
  }

  Drive.prototype.store = function(name, data) {
    return localStorage.setItem("typestart." + name, data);
  };

  Drive.prototype.load = function(name) {
    return localStorage.getItem("typestart." + name);
  };

  Drive.prototype.exists = function(name) {
    return localStorage.getItem("typestart." + name) != null;
  };

  Drive.prototype.remove = function(name) {
    if (this.exists(name)) {
      localStorage.removeItem("typestart." + name);
      return true;
    } else {
      return false;
    }
  };

  Drive.prototype.list = function() {
    var i, key, res, _i, _ref;
    res = [];
    for (i = _i = 0, _ref = localStorage.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      key = localStorage.key(i);
      if (key.indexOf("typestart.") === 0) {
        res.push(key.substring(10, key.length));
      }
    }
    return res;
  };

  return Drive;

})();
