// Generated by CoffeeScript 1.8.0
this.Editor = (function() {
  function Editor(typestart) {
    this.typestart = typestart;
    this.editor = ace.edit("editor");
    this.editor.setTheme("ace/theme/tomorrow_night_bright");
    this.editor.getSession().setMode("ace/mode/coffee");
    this.editor.getSession().on('change', (function(_this) {
      return function() {
        return _this.editorContentsChanged();
      };
    })(this));
    $("#editorcancelbutton").click((function(_this) {
      return function() {
        return _this.typestart.showTerminal();
      };
    })(this));
    $("#editorsavebutton").click((function(_this) {
      return function() {
        _this.typestart.drive.store(_this.typestart.current_project, _this.editor.getValue());
        return _this.typestart.showTerminal();
      };
    })(this));
  }

  Editor.prototype.edit = function(name) {
    var content;
    $("#editorfilename").html("editing: " + name);
    content = this.typestart.drive.load(name);
    if (content != null) {
      this.editor.setValue(content, 1);
    } else {
      this.editor.setValue("");
    }
    return this.typestart.showEditor();
  };

  Editor.prototype.editorContentsChanged = function() {};

  return Editor;

})();
